/* "Our Story" — the red string of fate. A pinned, horizontally-scrubbed timeline:
   the section pins and downward scroll pans the years leftward. Juriel rides the top
   lane, Grace Ann the bottom; the red string joins their mirrored childhoods (same
   bike, same glasses), pinches together the years they meet (2002, 2008), then knots
   into one line from 2015 to the proposal. Reduced-motion falls back to a vertical
   list. Photos come from window.W.storyAlbums (generated by tools/build-story.js);
   clicking a disc opens that milestone's album in the shared lightbox. */
(function () {
  "use strict";
  window.W = window.W || {};
  const geom = window.W.storyGeom;

  // The story. `key` links a node to its photos in window.W.storyAlbums.
  //  pair : a childhood match — a disc on each lane (his + hers), joined by the string
  //  kiss : the lanes touch here (a meeting before they were a couple)
  //  merge: from here the two lines fuse into one red string — the start of "us"
  //  gap  : a quiet break in the years (no photos), drawn as a marker on the string
  const STORY = [
    { pair: true, key: "bike",    label: "we had the same little bike" },
    { pair: true, key: "glasses", label: "and even the same glasses" },
    { who: "both", kiss: true,  key: "2002", year: 2002, caption: "We met in kindergarten" },
    { who: "both", kiss: true,  key: "2008", year: 2008, caption: "Mr. & Ms. Agham — won together" },
    { merge: true,              key: "2015", year: 2015, caption: "She said yes 💚 — it all started" },
    {                           key: "2016", year: 2016, caption: "Our first date" },
    {                           key: "2017", year: 2017, caption: "Enchanted Kingdom & graduation" },
    {                           key: "2018", year: 2018, caption: "Palawan, together" },
    {                           key: "2019", year: 2019, caption: "Siargao & our first glamp" },
    {                           key: "2020", year: 2020, caption: "Anniversary at home" },
    {                           key: "2021", year: 2021, caption: "Just the two of us" },
    {                           key: "2022", year: 2022, caption: "Coron anniversary · LANY" },
    {                           key: "2023", year: 2023, caption: "Mt. Pulag, Bohol, Cebu" },
    {                           key: "2024", year: 2024, caption: "La Union & Baguio" },
    {                           key: "2025", year: 2025, caption: "The proposal 💍" },
  ];

  const SVGNS = "http://www.w3.org/2000/svg";
  const el = (tag, cls) => { const e = document.createElement(tag); if (cls) e.className = cls; return e; };
  const svgEl = (tag, attrs) => {
    const e = document.createElementNS(SVGNS, tag);
    for (const k in attrs) e.setAttribute(k, attrs[k]);
    return e;
  };
  const albumFor = (key) => (window.W.storyAlbums && window.W.storyAlbums[key]) || {};

  // Fill a disc: the monogram always sits behind, so a missing/broken photo falls back
  // to it; a real photo loads on top and covers it.
  function fillDisc(disc, photo, glyphText) {
    disc.classList.add("is-empty");
    const glyph = el("span", "story-disc-glyph");
    glyph.textContent = glyphText;
    disc.appendChild(glyph);
    if (photo) {
      const img = el("img");
      img.alt = ""; img.loading = "lazy";
      img.onload = function () { disc.classList.remove("is-empty"); };
      img.onerror = function () { this.remove(); };
      img.src = photo;
      disc.appendChild(img);
    }
    return disc;
  }

  // make a disc open its album on click / Enter / Space
  function keyed(disc, key, role) {
    disc.setAttribute("data-key", key);
    if (role) disc.setAttribute("data-role", role);
    disc.setAttribute("role", "button");
    disc.setAttribute("tabindex", "0");
    disc.setAttribute("aria-label", "Open photos");
    return disc;
  }

  // a normal milestone (kiss or year): disc + tick to the line + year + caption
  function milestoneEl(n) {
    const wrap = el("div", "story-node " + (n.above ? "is-above" : "is-below") +
      (n.kiss ? " is-kiss" : "") + (n.data.merge ? " is-merge" : ""));
    wrap.style.left = n.x + "px";
    wrap.style.top = n.anchorY + "px";
    wrap.style.setProperty("--tick", Math.abs(n.laneY - n.anchorY) + "px");

    const disc = keyed(fillDisc(el("div", "story-disc"), albumFor(n.data.key).disc, "J & G"), n.data.key);
    const tick = el("span", "story-tick");
    const year = el("span", "story-year"); year.textContent = n.data.year;
    const cap = el("span", "story-caption"); cap.textContent = n.data.caption;

    if (n.above) { wrap.append(cap, year, disc, tick); }
    else { wrap.append(tick, disc, year, cap); }
    return wrap;
  }

  // a childhood matched pair: his disc on the top lane, hers on the bottom, joined by
  // a vertical red string, with one caption below.
  function pairEl(n, L) {
    const a = albumFor(n.data.key);
    const wrap = el("div", "story-node story-pair");
    wrap.style.left = n.x + "px";
    wrap.style.top = "0";
    wrap.style.height = L.band + "px";

    const string = el("div", "story-pair-string");
    string.style.top = L.topY + "px";
    string.style.height = (L.bottomY - L.topY) + "px";
    wrap.appendChild(string);

    const jLane = el("div", "story-pair-disc");
    jLane.style.top = L.topY + "px";
    jLane.appendChild(keyed(fillDisc(el("div", "story-disc"), a.juriel, "J"), n.data.key, "juriel"));
    wrap.appendChild(jLane);

    const gLane = el("div", "story-pair-disc");
    gLane.style.top = L.bottomY + "px";
    gLane.appendChild(keyed(fillDisc(el("div", "story-disc"), a.grace, "G"), n.data.key, "grace"));
    wrap.appendChild(gLane);

    const cap = el("span", "story-caption story-pair-caption");
    cap.textContent = n.data.label;
    cap.style.top = L.bottomY + "px";
    wrap.appendChild(cap);
    return wrap;
  }

  // a quiet gap in the years — a marker sitting on the red string
  function gapEl(n, L) {
    const wrap = el("div", "story-node story-gap");
    wrap.style.left = n.x + "px";
    wrap.style.top = L.centerY + "px";
    const dots = el("span", "story-gap-dots"); dots.textContent = "· · ·";
    const label = el("span", "story-gap-label"); label.textContent = n.data.label;
    wrap.append(dots, label);
    return wrap;
  }

  function nodeEl(n, L) {
    if (n.pair) return pairEl(n, L);
    if (n.gap) return gapEl(n, L);
    return milestoneEl(n);
  }

  // faint era captions floating over the track
  function labelEl(text, x, y, extra) {
    const lab = el("div", "story-era" + (extra ? " " + extra : ""));
    lab.textContent = text;
    lab.style.left = x + "px";
    lab.style.top = y + "px";
    return lab;
  }

  function StoryScene() {
    this.section = document.getElementById("story");
    this.scroll = document.getElementById("storyScroll");
    this.stage = document.getElementById("storyStage");
    this.track = document.getElementById("storyTrack");
    this.viewport = this.section ? this.section.querySelector(".story-viewport") : null;
    this.eased = 0; this.target = 0; this.pinScroll = 0; this.built = false;
  }

  StoryScene.prototype.build = function () {
    const vw = window.innerWidth, vh = window.innerHeight;
    const avail = (this.viewport && this.viewport.clientHeight) || vh;
    const L = geom.layout({ nodes: STORY, vw: vw, vh: avail });
    this.L = L;
    this.pinScroll = Math.max(0, L.width - vw);
    this.scroll.style.height = (vh + this.pinScroll) + "px";

    this.track.style.width = L.width + "px";
    this.track.style.height = L.band + "px";
    this.track.innerHTML = "";

    const svg = svgEl("svg", {
      class: "story-lines", width: L.width, height: L.band,
      viewBox: "0 0 " + L.width + " " + L.band, preserveAspectRatio: "none", "aria-hidden": "true",
    });
    svg.appendChild(svgEl("path", { class: "story-line story-line-j", d: L.paths.juriel }));
    svg.appendChild(svgEl("path", { class: "story-line story-line-g", d: L.paths.grace }));
    svg.appendChild(svgEl("path", { class: "story-line story-line-gold", d: L.paths.gold }));
    this.track.appendChild(svg);

    L.nodes.forEach((n) => this.track.appendChild(nodeEl(n, L)));

    // era labels: a banner above the childhood lanes, and one below the knot — both
    // kept clear of the discs (which grow upward from the centre line here)
    const first = L.nodes[0], merge = L.nodes[L.mergeIndex];
    if (first) this.track.appendChild(
      labelEl("before 2002 · we were already parallel", first.x - 30, 2, "is-prologue"));
    if (merge) this.track.appendChild(
      labelEl("2015 · it all started", merge.x, L.centerY + L.band * 0.26, "is-knot"));

    this.nodeEls = Array.prototype.slice.call(this.track.querySelectorAll(".story-node"));
    this.built = true;
    this.apply(true);
  };

  StoryScene.prototype.progress = function () {
    const rect = this.scroll.getBoundingClientRect();
    if (this.pinScroll <= 0) return 0;
    return geom.clamp(-rect.top / this.pinScroll, 0, 1);
  };

  StoryScene.prototype.apply = function (instant) {
    const panX = -this.eased * this.pinScroll;
    this.track.style.transform = "translate3d(" + panX + "px,-50%,0)";
    const vw = window.innerWidth;
    for (let i = 0; i < this.nodeEls.length; i++) {
      const n = this.L.nodes[i];
      const screenX = n.x + panX;
      if (screenX < vw * 0.9 && screenX > -vw * 0.3) this.nodeEls[i].classList.add("in");
    }
    if (this.head) this.head.style.opacity = String(geom.clamp(1 - this.eased * 3, 0.25, 1));
  };

  StoryScene.prototype.tick = function () {
    this.target = this.progress();
    this.eased += (this.target - this.eased) * 0.12;
    if (Math.abs(this.target - this.eased) < 0.0003) this.eased = this.target;
    this.apply(false);
  };

  // Swipe/drag the timeline sideways.
  //   The pan is 1:1 with page scroll (panX = -progress * pinScroll, and
  //   progress = scrolledIntoScene / pinScroll), so a horizontal drag of N px is
  //   simply N px of vertical scroll — dragging left walks the years forward.
  //   Vertical scrolling is untouched: `touch-action: pan-y` hands the browser the
  //   up/down gesture and keeps the sideways one for us, and Lenis only listens for
  //   vertical gestures so the two never fight.
  StoryScene.prototype.initSwipe = function () {
    const self = this;
    const el = this.viewport || this.stage;
    if (!el || !window.PointerEvent) return;

    const scrollBy = (dy) => {
      const l = window.__lenis;
      if (l) l.scrollTo(l.animatedScroll + dy, { immediate: true, force: true });
      else window.scrollTo(0, window.pageYOffset + dy);
    };

    let dragging = false, lastX = 0, travelled = 0;
    const DEAD = 6;   // px before a drag counts as a drag rather than a tap

    el.addEventListener("pointerdown", (e) => {
      if (e.pointerType === "mouse" && e.button !== 0) return;
      dragging = true; lastX = e.clientX; travelled = 0;
      el.classList.add("is-dragging");
      try { el.setPointerCapture(e.pointerId); } catch (_) {}
    });

    el.addEventListener("pointermove", (e) => {
      if (!dragging) return;
      const dx = e.clientX - lastX;
      if (!dx) return;
      lastX = e.clientX;
      travelled += Math.abs(dx);
      if (travelled > DEAD && e.cancelable) e.preventDefault();
      scrollBy(-dx);                       // drag left → story moves forward
    });

    const release = (e) => {
      if (!dragging) return;
      dragging = false;
      el.classList.remove("is-dragging");
      try { el.releasePointerCapture(e.pointerId); } catch (_) {}
      // a drag must not also open the disc it happened to start on
      self.dragged = travelled > DEAD;
      if (self.dragged) setTimeout(() => { self.dragged = false; }, 0);
    };
    el.addEventListener("pointerup", release);
    el.addEventListener("pointercancel", release);

    // trackpad / horizontal wheel — a sideways two-finger swipe pans the years too
    el.addEventListener("wheel", (e) => {
      if (Math.abs(e.deltaX) <= Math.abs(e.deltaY)) return;   // vertical: leave it to Lenis
      e.preventDefault();
      scrollBy(e.deltaX);
    }, { passive: false });
  };

  // open a disc's album in the shared lightbox (built in sections.js)
  StoryScene.prototype.openDisc = function (disc) {
    const key = disc.getAttribute("data-key");
    if (!key) return;
    const album = albumFor(key).album || [];
    if (!album.length || !window.W.openLightbox) return;
    const start = disc.getAttribute("data-role") === "grace" ? 1 : 0;
    window.W.openLightbox(album, start);
  };

  StoryScene.prototype.init = function () {
    if (!this.section) return;
    const self = this;
    this.head = this.section.querySelector(".story-head");
    window.__story = this;
    this.build();

    this.initSwipe();

    // discs open their album — attached to the persistent track, so it survives rebuilds
    this.track.addEventListener("click", (e) => {
      if (self.dragged) return;                  // that click was the end of a swipe
      const disc = e.target.closest(".story-disc"); if (disc) self.openDisc(disc);
    });
    this.track.addEventListener("keydown", (e) => {
      if (e.key !== "Enter" && e.key !== " ") return;
      const disc = e.target.closest(".story-disc"); if (disc) { e.preventDefault(); self.openDisc(disc); }
    });

    const skip = document.getElementById("storySkip");
    if (skip) skip.addEventListener("click", () => {
      if (window.W.cardOpened) window.W.cardOpened();  // deliberate jump — lift the card gate
      const g = document.getElementById("gallery");
      if (window.__lenis && g) window.__lenis.scrollTo(g, { duration: 1.2 });
      else if (g) g.scrollIntoView({ behavior: "smooth" });
    });

    let rt;
    window.addEventListener("resize", () => { clearTimeout(rt); rt = setTimeout(() => self.build(), 200); });
    requestAnimationFrame(function loop() { self.tick(); requestAnimationFrame(loop); });
  };

  // reduced-motion: a calm vertical list of the moments (pairs show his + hers).
  StoryScene.prototype.initLite = function () {
    if (!this.section) return;
    const self = this;
    this.section.classList.add("story--lite");
    this.scroll.style.height = "auto";
    this.track.style.cssText = "";
    this.track.innerHTML = "";
    const list = el("ol", "story-list");
    STORY.forEach((n) => {
      if (n.gap) return;
      const a = albumFor(n.key);
      const li = el("li", "story-list-item");
      if (n.pair) {
        li.appendChild(keyed(fillDisc(el("div", "story-disc"), a.juriel, "J"), n.key, "juriel"));
        li.appendChild(keyed(fillDisc(el("div", "story-disc"), a.grace, "G"), n.key, "grace"));
      } else {
        li.appendChild(keyed(fillDisc(el("div", "story-disc"), a.disc, "J & G"), n.key));
      }
      const txt = el("div", "story-list-text");
      if (n.year) { const year = el("span", "story-year"); year.textContent = n.year; txt.appendChild(year); }
      const cap = el("span", "story-caption"); cap.textContent = n.caption || n.label;
      txt.appendChild(cap);
      li.append(txt);
      list.appendChild(li);
    });
    this.track.appendChild(list);
    this.track.addEventListener("click", (e) => {
      const disc = e.target.closest(".story-disc"); if (disc) self.openDisc(disc);
    });
    const skip = document.getElementById("storySkip");
    if (skip) skip.style.display = "none";
  };

  window.W.StoryScene = StoryScene;
})();
