/* "Our Story" — the red string of fate, falling down the page. The years walk forward
   as you scroll: the section is as tall as the timeline needs (about two and a half
   screens), so reading it is just reading the page. Juriel rides the left lane, Grace
   Ann the right; the red string joins their mirrored childhoods (same bike, glasses),
   pinches together the years they meet (2002, 2008), then knots into one line from
   2015 to the proposal. Milestones fade in as they come into view; reduced motion
   simply shows them all at once. The string is centred at every width — on a narrow
   screen each milestone stacks its text under its disc rather than beside it, see
   storyGeometry.js. Photos come from window.W.storyAlbums (generated by
   tools/build-story.js); clicking a disc opens that milestone's album in the shared
   lightbox. */
(function () {
  "use strict";
  window.W = window.W || {};
  const geom = window.W.storyGeom;

  // The story. `key` links a node to its photos in window.W.storyAlbums.
  //  pair : a childhood match — a disc on each lane (his + hers), joined by the string
  //  kiss : the lanes touch here (a meeting before they were a couple)
  //  merge: from here the two lines fuse into one red string — the start of "us"
  //  gap  : a quiet break in the years (no photos), drawn as a marker on the string
  const STORY = [
    { pair: true, key: "bike",    label: "we had the same little bike" },
    { pair: true, key: "glasses", label: "and even the same glasses" },
    { who: "both", kiss: true,  key: "2002", year: 2002, caption: "We met in kindergarten" },
    { who: "both", kiss: true,  key: "2008", year: 2008, caption: "Mr. & Ms. Agham — won together" },
    { merge: true,              key: "2015", year: 2015, era: "it all started",
                                caption: "She said yes 💚 — it all started" },
    {                           key: "2016", year: 2016, caption: "Our first date" },
    {                           key: "2017", year: 2017, caption: "Enchanted Kingdom & graduation" },
    {                           key: "2018", year: 2018, caption: "Palawan, together" },
    {                           key: "2019", year: 2019, caption: "Siargao & our first glamp" },
    {                           key: "2020", year: 2020, caption: "Anniversary at home" },
    {                           key: "2021", year: 2021, caption: "Just the two of us" },
    {                           key: "2022", year: 2022, caption: "Coron anniversary · LANY" },
    {                           key: "2023", year: 2023, caption: "Mt. Pulag, Bohol, Cebu" },
    {                           key: "2024", year: 2024, caption: "La Union & Baguio" },
    {                           key: "2025", year: 2025, caption: "The proposal 💍" },
  ];

  const SVGNS = "http://www.w3.org/2000/svg";
  const el = (tag, cls) => { const e = document.createElement(tag); if (cls) e.className = cls; return e; };
  const svgEl = (tag, attrs) => {
    const e = document.createElementNS(SVGNS, tag);
    for (const k in attrs) e.setAttribute(k, attrs[k]);
    return e;
  };
  const albumFor = (key) => (window.W.storyAlbums && window.W.storyAlbums[key]) || {};

  // Fill a disc: the monogram always sits behind, so a missing/broken photo falls back
  // to it; a real photo loads on top and covers it.
  function fillDisc(disc, photo, glyphText) {
    disc.classList.add("is-empty");
    const glyph = el("span", "story-disc-glyph");
    glyph.textContent = glyphText;
    disc.appendChild(glyph);
    if (photo) {
      const img = el("img");
      img.alt = ""; img.loading = "lazy";
      img.onload = function () { disc.classList.remove("is-empty"); };
      img.onerror = function () { this.remove(); };
      img.src = photo;
      disc.appendChild(img);
    }
    return disc;
  }

  // make a disc open its album on click / Enter / Space
  function keyed(disc, key, role) {
    disc.setAttribute("data-key", key);
    if (role) disc.setAttribute("data-role", role);
    disc.setAttribute("role", "button");
    disc.setAttribute("tabindex", "0");
    disc.setAttribute("aria-label", "Open photos");
    return disc;
  }

  // a normal milestone (kiss or year): a tick out to the disc, then the year + caption
  // beyond it. The wrapper sits on the string and grows sideways — left for is-left,
  // right for is-right — so the tick always starts at the line.
  function milestoneEl(n) {
    const wrap = el("div", "story-node " + (n.left ? "is-left" : "is-right") +
      (n.kiss ? " is-kiss" : "") + (n.data.merge ? " is-merge" : ""));
    wrap.style.top = n.y + "px";
    wrap.style.left = n.anchorX + "px";
    wrap.style.setProperty("--tick", Math.abs(n.laneX - n.anchorX) + "px");

    const disc = keyed(fillDisc(el("div", "story-disc"), albumFor(n.data.key).disc, "J & G"), n.data.key);
    const tick = el("span", "story-tick");
    const text = el("div", "story-node-text");
    // an era marker belongs to its milestone, above the year — floating it out over the
    // string put it where the two lifelines cross and made it unreadable
    if (n.data.era) {
      const era = el("span", "story-node-era"); era.textContent = n.data.era;
      text.appendChild(era);
    }
    if (n.data.year) {
      const year = el("span", "story-year"); year.textContent = n.data.year;
      text.appendChild(year);
    }
    const cap = el("span", "story-caption"); cap.textContent = n.data.caption;
    text.appendChild(cap);

    // one order in the DOM; is-left reverses the row in CSS, so the tick still touches
    // the string and the text still ends up furthest from it
    wrap.append(tick, disc, text);
    return wrap;
  }

  // a childhood matched pair: his disc on one lane, hers on the other, joined by a
  // horizontal red string, with one caption underneath.
  function pairEl(n, L) {
    const a = albumFor(n.data.key);
    const wrap = el("div", "story-node story-pair");
    wrap.style.top = n.y + "px";
    wrap.style.left = "0";
    wrap.style.width = L.band + "px";

    const string = el("div", "story-pair-string");
    string.style.left = n.pairX.juriel + "px";
    string.style.width = (n.pairX.grace - n.pairX.juriel) + "px";
    wrap.appendChild(string);

    const jLane = el("div", "story-pair-disc");
    jLane.style.left = n.pairX.juriel + "px";
    jLane.appendChild(keyed(fillDisc(el("div", "story-disc"), a.juriel, "J"), n.data.key, "juriel"));
    wrap.appendChild(jLane);

    const gLane = el("div", "story-pair-disc");
    gLane.style.left = n.pairX.grace + "px";
    gLane.appendChild(keyed(fillDisc(el("div", "story-disc"), a.grace, "G"), n.data.key, "grace"));
    wrap.appendChild(gLane);

    const cap = el("span", "story-caption story-pair-caption");
    cap.textContent = n.data.label;
    cap.style.left = n.pairMid + "px";
    wrap.appendChild(cap);
    return wrap;
  }

  // a quiet gap in the years — a marker sitting on the red string
  function gapEl(n) {
    const wrap = el("div", "story-node story-gap " + (n.left ? "is-left" : "is-right"));
    wrap.style.top = n.y + "px";
    wrap.style.left = n.anchorX + "px";
    const dots = el("span", "story-gap-dots"); dots.textContent = "· · ·";
    const label = el("span", "story-gap-label"); label.textContent = n.data.label;
    wrap.append(dots, label);
    return wrap;
  }

  function nodeEl(n, L) {
    if (n.pair) return pairEl(n, L);
    if (n.gap) return gapEl(n);
    return milestoneEl(n);
  }

  // the one faint era label floating over the lanes, before they have met
  function labelEl(text, x, y, extra) {
    const lab = el("div", "story-era" + (extra ? " " + extra : ""));
    lab.textContent = text;
    lab.style.left = x + "px";
    lab.style.top = y + "px";
    return lab;
  }

  function StoryScene() {
    this.section = document.getElementById("story");
    this.track = document.getElementById("storyTrack");
    this.built = false;
    this.lite = false;
    this.io = null;
  }

  StoryScene.prototype.build = function () {
    const L = geom.layout({ nodes: STORY, vw: window.innerWidth, vh: window.innerHeight });
    this.L = L;

    this.track.style.width = L.band + "px";
    this.track.style.height = L.height + "px";
    // narrow screens stack each milestone's text under its disc instead of beside it
    this.track.classList.toggle("is-stacked", L.stack);
    this.track.innerHTML = "";

    const svg = svgEl("svg", {
      class: "story-lines", width: L.band, height: L.height,
      viewBox: "0 0 " + L.band + " " + L.height, "aria-hidden": "true",
    });
    svg.appendChild(svgEl("path", { class: "story-line story-line-j", d: L.paths.juriel }));
    svg.appendChild(svgEl("path", { class: "story-line story-line-g", d: L.paths.grace }));
    svg.appendChild(svgEl("path", { class: "story-line story-line-gold", d: L.paths.gold }));
    this.track.appendChild(svg);

    L.nodes.forEach((n) => this.track.appendChild(nodeEl(n, L)));

    // one era label, over the top of the two lanes before they have met. The knot's
    // own marker rides inside the 2015 milestone instead (see `era` in STORY).
    const first = L.nodes[0];
    if (first) this.track.appendChild(
      labelEl("before 2002 · we were already parallel", L.centerX,
              Math.max(10, first.y - L.gap * 0.55), "is-prologue"));

    this.reveal();
    this.built = true;
  };

  // Fade each milestone in as it arrives. Anything already at or above the fold is
  // shown outright — on a rebuild (resize) or a deep link, everything the visitor has
  // scrolled past is off-screen above and would never trip the observer.
  StoryScene.prototype.reveal = function () {
    const nodes = Array.prototype.slice.call(this.track.querySelectorAll(".story-node"));
    if (this.io) this.io.disconnect();
    if (this.lite) { nodes.forEach((n) => n.classList.add("in")); return; }

    const fold = window.innerHeight;
    const pending = [];
    nodes.forEach((n) => {
      if (n.getBoundingClientRect().top < fold) n.classList.add("in");
      else pending.push(n);
    });
    if (!pending.length || !window.IntersectionObserver) {
      pending.forEach((n) => n.classList.add("in"));
      return;
    }
    // same rule as the site's other reveals (sections.js), pulled in a little so a
    // milestone has settled before it lights up
    this.io = new IntersectionObserver((es) => {
      es.forEach((e) => {
        if (!e.isIntersecting) return;
        e.target.classList.add("in");
        this.io.unobserve(e.target);
      });
    }, { threshold: 0.2, rootMargin: "0px 0px -6% 0px" });
    pending.forEach((n) => this.io.observe(n));
  };

  // open a disc's album in the shared lightbox (built in sections.js)
  StoryScene.prototype.openDisc = function (disc) {
    const key = disc.getAttribute("data-key");
    if (!key) return;
    const album = albumFor(key).album || [];
    if (!album.length || !window.W.openLightbox) return;
    const start = disc.getAttribute("data-role") === "grace" ? 1 : 0;
    window.W.openLightbox(album, start);
  };

  // discs open their album — attached to the persistent track, so it survives rebuilds
  StoryScene.prototype.bindDiscs = function () {
    const self = this;
    this.track.addEventListener("click", (e) => {
      const disc = e.target.closest(".story-disc"); if (disc) self.openDisc(disc);
    });
    this.track.addEventListener("keydown", (e) => {
      if (e.key !== "Enter" && e.key !== " ") return;
      const disc = e.target.closest(".story-disc"); if (disc) { e.preventDefault(); self.openDisc(disc); }
    });
  };

  StoryScene.prototype.init = function () {
    if (!this.section) return;
    const self = this;
    window.__story = this;
    this.build();
    this.bindDiscs();

    // The band and the spacing are both measured from the viewport, so a resize (or a
    // phone turning landscape) has to re-lay the whole timeline.
    let rt;
    window.addEventListener("resize", () => { clearTimeout(rt); rt = setTimeout(() => self.build(), 200); });
  };

  // reduced-motion: the same timeline, with every milestone already shown — no fades,
  // nothing that waits on scrolling.
  StoryScene.prototype.initLite = function () {
    if (!this.section) return;
    this.lite = true;
    this.section.classList.add("story--lite");
    this.init();
  };

  window.W.StoryScene = StoryScene;
})();
