/* GENERATED by tools/build-story.js — do not edit by hand. */
window.W = window.W || {};
window.W.storyAlbums = {
  "2002": {
    "disc": "media/story/2002/disc.jpg",
    "album": [
      "media/story/2002/01.jpg"
    ]
  },
  "2008": {
    "disc": "media/story/2008/disc.jpg",
    "album": [
      "media/story/2008/01.jpg"
    ]
  },
  "2015": {
    "disc": "media/story/2015/disc.jpg",
    "album": [
      "media/story/2015/01.jpg",
      "media/story/2015/02.jpg"
    ]
  },
  "2016": {
    "disc": "media/story/2016/disc.jpg",
    "album": [
      "media/story/2016/01.jpg",
      "media/story/2016/02.jpg",
      "media/story/2016/03.jpg",
      "media/story/2016/04.jpg"
    ]
  },
  "2017": {
    "disc": "media/story/2017/disc.jpg",
    "album": [
      "media/story/2017/01.jpg",
      "media/story/2017/02.jpg",
      "media/story/2017/03.jpg",
      "media/story/2017/04.jpg",
      "media/story/2017/05.jpg"
    ]
  },
  "2018": {
    "disc": "media/story/2018/disc.jpg",
    "album": [
      "media/story/2018/01.jpg",
      "media/story/2018/02.jpg",
      "media/story/2018/03.jpg"
    ]
  },
  "2019": {
    "disc": "media/story/2019/disc.jpg",
    "album": [
      "media/story/2019/01.jpg",
      "media/story/2019/02.jpg"
    ]
  },
  "2020": {
    "disc": "media/story/2020/disc.jpg",
    "album": [
      "media/story/2020/01.jpg",
      "media/story/2020/02.jpg",
      "media/story/2020/03.jpg"
    ]
  },
  "2021": {
    "disc": "media/story/2021/disc.jpg",
    "album": [
      "media/story/2021/01.jpg",
      "media/story/2021/02.jpg"
    ]
  },
  "2022": {
    "disc": "media/story/2022/disc.jpg",
    "album": [
      "media/story/2022/01.jpg",
      "media/story/2022/02.jpg",
      "media/story/2022/03.jpg",
      "media/story/2022/04.jpg"
    ]
  },
  "2023": {
    "disc": "media/story/2023/disc.jpg",
    "album": [
      "media/story/2023/01.jpg",
      "media/story/2023/02.jpg",
      "media/story/2023/03.jpg",
      "media/story/2023/04.jpg"
    ]
  },
  "2024": {
    "disc": "media/story/2024/disc.jpg",
    "album": [
      "media/story/2024/01.jpg",
      "media/story/2024/02.jpg",
      "media/story/2024/03.jpg"
    ]
  },
  "2025": {
    "disc": "media/story/2025/disc.jpg",
    "album": [
      "media/story/2025/01.jpg",
      "media/story/2025/02.jpg",
      "media/story/2025/03.jpg",
      "media/story/2025/04.jpg"
    ]
  },
  "bike": {
    "pair": true,
    "juriel": "media/story/bike/disc-juriel.jpg",
    "grace": "media/story/bike/disc-grace.jpg",
    "album": [
      "media/story/bike/01.jpg",
      "media/story/bike/02.jpg"
    ]
  },
  "glasses": {
    "pair": true,
    "juriel": "media/story/glasses/disc-juriel.jpg",
    "grace": "media/story/glasses/disc-grace.jpg",
    "album": [
      "media/story/glasses/01.jpg",
      "media/story/glasses/02.jpg"
    ]
  }
};
